### ISSUE TITLE
Update minichlink.exe to the latest to support the debug input!

### ISSUE THREAD

**Issue by arduino12** [Community-PIO-CH32V/tool-minichlink#1]
**Hi,**

I use Windows11 + ESP32-S2-MINI programmer.

@maxgerhardt 
When I use the minichlink.exe (4.74 MB) from the PlatformIO, the [debug input](https://github.com/cnlohr/ch32v003fun/blob/master/examples/debugprintfdemo/debugprintfdemo.c#L10) doesn't work :(

But when I use the [minichlink.exe](https://github.com/cnlohr/ch32v003fun/blob/master/minichlink/minichlink.exe) (103 KB) from ch32v003fun it works!

So please update the minichlink.exe to the latest one from ch32v003fun..
**Thanks :)**

**Comment by maxgerhardt** [comment]
Thanks for letting me know, will try and update binaries for all OSes today.

**Comment by arduino12** [comment]
I still get the old minichlink.exe (4.74 MB) when I re-install the package.

Also better add a note to the main branch README that the binaries for each OS are only committed in the matching OS branch :)

**:)**

**Comment by maxgerhardt** [comment]
Woops forgot about. This is now fixed in https://github.com/Community-PIO-CH32V/tool-minichlink/commit/3d2abd22d3cc048ee0d9e0777cb9802a10c98eb3, https://github.com/Community-PIO-CH32V/tool-minichlink/commit/b8bb9b0462fbef7bbf88c78ed2ce789b02ebc1e4 and https://github.com/Community-PIO-CH32V/tool-minichlink/commit/6995801a69466d2acd0dab3a0830463c96cb353c.

To get the update, the old package folder can simply be deleted, and then a "Upload" should be triggered in the PIO project.
```
rm -rf ~/.platformio/packages/tool-minichlink
```
